SharpeningSize: 2
SharpeningSigma: 1.1
ApplyFilterOn:
- Checkbox
- CheckboxDown
- CheckboxOver
- Check
- Property
- Type_Class
- Interface
- LockIcon
- RedDotUnbound
- RedDot
- Field
- MoreInfo
- Workspace
- Method
- IconValue
- IconPointer
# - IconPayloadEnum
- RedDotEx
- RedDotExDisabled
- RedDotExUnbound
- RedDotRunToCursor